### ISSUE TITLE
vc-storefront IIS deployment

### ISSUE THREAD

**Issue by satwinder8294** [VirtoCommerce/vc-storefront#621]
I am trying to deploy vc-storefront on IIS server. I am following the YouTube tutorial given in below URL

https://www.youtube.com/watch?v=BDpRec7_p7g

It works fine till I run publish command.  The publish command runs successfully and the files gets generated in given folder. The command ran to publish the video is "**dotnet publish -o <storefront>**"

In video, right after they ran this command they open a URL "http://localhost/admin" , which does not work in my case. Can someone please help me to get rid of this roadblock ? I am stuck at this point and don't know how to proceed.

Note: If you feel this is not right place to ask this question, please suggest where can I get some help regarding this.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8195 has been created

**Comment by satwinder8294** [comment]
@mvktsk can you please elaborate what you just commented above ?

**Comment by OlegoO** [comment]
@satwinder8294  
The video is out-of-date. Please folow this links and recommendations for .NET 6 deployment.

https://docs.virtocommerce.org/vc-quickstart/
https://docs.virtocommerce.org/getting-started/connect-storefront-to-platform-v3/

**Comment by satwinder8294** [comment]
@OlegoO  thank you for the response. I followed the 2nd link was able to run it (see attached screenshot). But this runs on local only. I want to know how to publish it and deploy on the IIS server. Please help me with that.

![image](https://user-images.githubusercontent.com/63798094/193342163-e8846583-7cbd-4c5c-8abf-251726f1877b.png)

**Comment by OlegoO** [comment]
@satwinder8294  Unfortunately, we did not used IIS, more. Our team works with cloud environments: Azure, Amazon, K8, etc. 

Because Virto Storefront and Platform are based on .NET 6 and ASP.NET Core, I recommend to check Microsoft recommendations:
https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-6.0
https://learn.microsoft.com/en-us/aspnet/core/tutorials/publish-to-iis?view=aspnetcore-6.0&tabs=visual-studio

and other posts:
https://www.c-sharpcorner.com/article/host-and-publish-net-core-6-web-api-application-on-iis-server2/

if you are able to run on IIS, I recommend to share your step by step solution on VC community https://www.virtocommerce.org/
